# Generated by Django 3.2.3 on 2021-05-27 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0003_auto_20210527_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lnews.basemodel')),
                ('media', models.ImageField(help_text='Image/Document/Video', upload_to='', verbose_name='Media')),
                ('news_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lnews.news')),
            ],
            bases=('lnews.basemodel',),
        ),
    ]
