# Generated by Django 3.2.3 on 2021-05-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0004_newsmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmedia',
            name='news_item',
        ),
        migrations.AddField(
            model_name='newsmedia',
            name='base_news',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_media_news', to='lnews.news'),
        ),
    ]
