# Generated by Django 3.2.3 on 2021-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0005_auto_20210527_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(default=None, max_length=1000000, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=1024, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
