# Generated by Django 3.2.3 on 2021-05-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0007_auto_20210527_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, max_length=10, to='lnews.NewsCategory'),
        ),
    ]
