# Generated by Django 3.2.3 on 2021-05-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0008_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main_category',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_main_category', to='lnews.newscategory'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, max_length=10, related_name='news_subcategories', to='lnews.NewsCategory'),
        ),
    ]
