# Generated by Django 3.2.3 on 2021-05-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0009_auto_20210527_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News List'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'News category', 'verbose_name_plural': 'News categories'},
        ),
        migrations.AlterModelOptions(
            name='newsmedia',
            options={'verbose_name': 'News media', 'verbose_name_plural': 'News Media'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
    ]
