# Generated by Django 3.2.3 on 2021-05-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0010_auto_20210527_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News list'},
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Country name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='title',
            field=models.CharField(help_text='Category title', max_length=1024, verbose_name='Category name'),
        ),
    ]
