# Generated by Django 3.2.3 on 2021-05-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0011_auto_20210527_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='banner',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='newsmedia',
            name='media_doc',
            field=models.FileField(default=None, help_text='Document/Video', null=True, upload_to='', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(default=None, max_length=1000000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='newsmedia',
            name='media',
            field=models.ImageField(help_text='Only for photo', upload_to='', verbose_name='Photo'),
        ),
    ]
