# Generated by Django 3.2.3 on 2021-05-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0012_auto_20210527_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmedia',
            options={'verbose_name': 'Media list', 'verbose_name_plural': 'Media'},
        ),
        migrations.RemoveField(
            model_name='newsmedia',
            name='base_news',
        ),
        migrations.RemoveField(
            model_name='newsmedia',
            name='media_doc',
        ),
        migrations.AlterField(
            model_name='newsmedia',
            name='media',
            field=models.FileField(default=None, help_text='Photo/Document/Video/Audio', null=True, upload_to='', verbose_name='Document'),
        ),
    ]
