# Generated by Django 3.2.3 on 2021-05-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0013_auto_20210527_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='category_image',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Category image'),
        ),
    ]
