# Generated by Django 3.2.3 on 2021-05-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0014_newscategory_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='number_of_watches',
            field=models.IntegerField(default=0, verbose_name='Watch count'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lnews.basemodel')),
                ('comment_body', models.TextField(default=None, null=True, verbose_name='Comment')),
                ('commenting_news', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lnews.news', verbose_name='News')),
                ('replying_comment', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lnews.comment')),
            ],
            bases=('lnews.basemodel',),
        ),
    ]
