# Generated by Django 3.2.3 on 2021-05-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0015_auto_20210527_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenting_news',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lnews.news', verbose_name='News'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_main_category', to='lnews.newscategory'),
        ),
    ]
