# Generated by Django 3.2.3 on 2021-05-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0016_auto_20210527_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replying_comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lnews.comment'),
        ),
    ]
