# Generated by Django 3.2.3 on 2021-05-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0017_alter_comment_replying_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replying_comment',
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lnews.basemodel')),
                ('comment_body', models.TextField(default=None, null=True, verbose_name='Reply')),
                ('comment_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lnews.comment', verbose_name='Comment')),
            ],
            bases=('lnews.basemodel',),
        ),
    ]
