# Generated by Django 3.2.4 on 2021-06-10 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnews', '0018_auto_20210527_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteNews',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lnews.basemodel')),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_item_favorite_by', to=settings.AUTH_USER_MODEL)),
                ('fav_news', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_item_favorite', to='lnews.news')),
            ],
            options={
                'unique_together': {('fav_news', 'by_user')},
            },
            bases=('lnews.basemodel',),
        ),
    ]
